blueprint:
  name: ZHA - IKEA Remote
  description: |
    Controll lights and other with IKEA Trådfri Remote (round)

  domain: automation
  input:
    remote:
      name: Remote
      description: Namron controller
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: 'TRADFRI remote control'

#--------------------ON----------------------------------------         
    on_short:
      name: on button - short press
      description: Action to run on short press on one on button 
      default: []
      selector:
        action:
    on_long:
      name: on button - long press
      description: Action to run on long press on one on button 
      default: []
      selector:
        action:    
    on_long_stop:
      name: on button - long press release
      description: Action to run on long press release on one on button 
      default: []
      selector:
        action:   
#--------------------OFF----------------------------------------         
    off_short:
      name: off button - short press
      description: Action to run on short press on One off button 
      default: []
      selector:
        action:
    off_long:
      name: off button - long press
      description: Action to run on long press on One off button 
      default: []
      selector:
        action:
    off_long_stop:
      name: off button - long press release
      description: Action to run on long press release on One off button 
      default: []
      selector:
        action:
#--------------------RIGHT---------------------------------------- 
    right_short:
      name: right button - short press
      description: Action to run on short press on One off button 
      default: []
      selector:
        action:
    right_long:
      name: right button - long press
      description: Action to run on long press on One off button 
      default: []
      selector:
        action:
    right_long_stop:
      name: right button - long press release
      description: Action to run on long press release on One off button 
      default: []
      selector:
        action:
#--------------------LEFT---------------------------------------- 
    left_short:
      name: left button - short press
      description: Action to run on short press on One off button 
      default: []
      selector:
        action:
    left_long:
      name: left button - long press
      description: Action to run on long press on One off button 
      default: []
      selector:
        action:
    left_long_stop:
      name: left button - long press release
      description: Action to run on long press release on One off button 
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent


trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
      move_mode: "{{ trigger.event.data.params.move_mode }}"
  - choose:


#--------------------ON SHORT----------------------------------------
      - conditions:
          - "{{ command == 'step_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input on_short

#--------------------ON LONG----------------------------------------
      - conditions:
          - "{{ command == 'move_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ move_mode == 'MoveMode.Up' }}"
        sequence: !input on_long

#--------------------ON LONG RELEASE----------------------------------------        
      - conditions:
          - "{{ command == 'stop_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input on_long_stop

#--------------------OFF SHORT---------------------------------------- 
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input off_short

#--------------------OFF LONG---------------------------------------- 
      - conditions:
          - "{{ command == 'move' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ move_mode == 'MoveMode.Down' }}"
        sequence: !input off_long

#--------------------OFF LONG RELEASE----------------------------------------         
      - conditions:
          - "{{ command == 'stop' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input off_long_stop

#--------------------RIGHT SHORT----------------------------------------         
      - conditions:
          - "{{ command == 'press' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [256, 13, 0] }}"
        sequence: !input right_short
#--------------------RIGHT LONG----------------------------------------         
      - conditions:
          - "{{ command == 'hold' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [3328, 0] }}"
        sequence: !input right_long
#--------------------RIGHT LONG RELEASE----------------------------------------         
      - conditions:
          - "{{ command == 'release' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input right_long_stop
#--------------------LEFT----------------------------------------         
      - conditions:
          - "{{ command == 'press' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [257, 13, 0] }}"
        sequence: !input off_long_stop
#--------------------LEFT LONG----------------------------------------         
      - conditions:
          - "{{ command == 'hold' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [3329, 0] }}"
        sequence: !input off_long_stop
#--------------------LEFT LONG RELEASE----------------------------------------         
      - conditions:
          - "{{ command == 'release' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input off_long_stop
