blueprint:
  name: ZHA - IKEA Remote
  description: |
    Controll lights and other with IKEA Trådfri Remote (round)

  domain: automation
  input:
    remote:
      name: Remote
      description: Namron controller
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: 'TRADFRI remote control'

#--------------------TOGGLE----------------------------------------         
    toggle_short:
      name: toggle button
      description: Action to run on toggle button 
      default: []
      selector:
        action:
#--------------------UP----------------------------------------         
    up_short:
      name: up button - short press
      description: Action to run on short press on up button 
      default: []
      selector:
        action:
    up_long:
      name: up button - long press
      description: Action to run on long press on up button 
      default: []
      selector:
        action:    
    up_long_stop:
      name: up button - long press release
      description: Action to run on long press release on up button 
      default: []
      selector:
        action:   
#--------------------DOWN----------------------------------------         
    down_short:
      name: down button - short press
      description: Action to run on short press on down button 
      default: []
      selector:
        action:
    down_long:
      name: down button - long press
      description: Action to run on long press on down button 
      default: []
      selector:
        action:
    down_long_stop:
      name: down button - long press release
      description: Action to run on long press release on down button 
      default: []
      selector:
        action:
#--------------------RIGHT---------------------------------------- 
    right_short:
      name: right button - short press
      description: Action to run on short press on right button 
      default: []
      selector:
        action:
    right_long:
      name: right button - long press
      description: Action to run on long press on right button 
      default: []
      selector:
        action:
    right_long_stop:
      name: right button - long press release
      description: Action to run on long press release on right button 
      default: []
      selector:
        action:
#--------------------LEFT---------------------------------------- 
    left_short:
      name: left button - short press
      description: Action to run on short press on left button 
      default: []
      selector:
        action:
    left_long:
      name: left button - long press
      description: Action to run on long press on left button 
      default: []
      selector:
        action:
    left_long_stop:
      name: left button - long press release
      description: Action to run on long press release on left button 
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent


trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
      move_mode: "{{ trigger.event.data.params.move_mode }}"
  - choose:

#--------------------TOGGLE----------------------------------------
      - conditions:
          - "{{ command == 'toggle' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input toggle_short
#--------------------UP SHORT----------------------------------------
      - conditions:
          - "{{ command == 'step_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input up_short

#--------------------UP LONG----------------------------------------
      - conditions:
          - "{{ command == 'move_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ move_mode == 'MoveMode.Up' }}"
        sequence: !input up_long

#--------------------UP LONG RELEASE----------------------------------------        
      - conditions:
          - "{{ command == 'stop_with_on_off' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input up_long_stop

#--------------------DOWN SHORT---------------------------------------- 
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input down_short

#--------------------DOWN LONG---------------------------------------- 
      - conditions:
          - "{{ command == 'move' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ move_mode == 'MoveMode.Down' }}"
        sequence: !input down_long

#--------------------DOWN LONG RELEASE----------------------------------------         
      - conditions:
          - "{{ command == 'stop' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input down_long_stop

#--------------------RIGHT SHORT----------------------------------------         
      - conditions:
          - "{{ command == 'press' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [256, 13, 0] }}"
        sequence: !input right_short
#--------------------RIGHT LONG----------------------------------------         
      - conditions:
          - "{{ command == 'hold' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [3328, 0] }}"
        sequence: !input right_long
#--------------------RIGHT LONG RELEASE----------------------------------------         
      - conditions:
          - "{{ command == 'release' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input right_long_stop
#--------------------LEFT----------------------------------------         
      - conditions:
          - "{{ command == 'press' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [257, 13, 0] }}"
        sequence: !input left_short
#--------------------LEFT LONG----------------------------------------         
      - conditions:
          - "{{ command == 'hold' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [3329, 0] }}"
        sequence: !input left_long
#--------------------LEFT LONG RELEASE----------------------------------------         
      - conditions:
          - "{{ command == 'release' }}"
          - "{{ cluster_id == 5 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ args == [] }}"
        sequence: !input left_long_stop
